name: newsy
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  #dependecies
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  onboarding: ^4.0.2
  flutter_spinkit: ^5.2.2
  introduction_screen: ^4.0.0
  flutter_svg: ^2.2.1
  otp_pin_field: ^1.4.1
  pinput: ^5.0.2
  country_picker: ^2.0.27
  intl: ^0.20.2
  grouped_list: ^6.0.0
  share_plus: ^12.0.0
  cached_network_image: ^3.4.1
  mobkit_dashed_border: ^0.0.8
  flutter_quill: ^11.4.2
  flutter_quill_extensions: ^11.0.0
  image_picker: ^1.2.0

  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  generate: true 


  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/auth/
    - assets/images/logo/
    - assets/images/onboarding/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

  